### ISSUE TITLE
Parser bug on page?

### ISSUE THREAD

**Issue by getify** [clarity-lang/book#18]
I was playing around with different approaches to the "quiz" on the ["Read Only Functions" page](https://book.clarity-lang.org/ch05-03-read-only-functions.html). And I had this code entered:

```clarity
(define-map counters principal uint)

(map-set counters 'ST1J4G6RR643BCG8G8SR6M2D9Z9KXT2NJDRK3FBTK u5)
(map-set counters 'ST20ATRN26N9P05V2F1RHFRV24X8C8M3W54E427B2 u10)

(define-read-only (get-counter-of (who principal))
	(begin
		(asserts! (not (is-eq (map-get? counters who) none)) u0)
		(unwrap-panic (map-get? counters who))
	)
	
;;	(if (is-eq (map-get? counters who) none)
;;		u0
;;		(unwrap-panic (map-get? counters who))
;;	)

)

;; These exist:
(print (get-counter-of 'ST1J4G6RR643BCG8G8SR6M2D9Z9KXT2NJDRK3FBTK))
(print (get-counter-of 'ST20ATRN26N9P05V2F1RHFRV24X8C8M3W54E427B2))

;; This one does not:
(print (get-counter-of 'ST21HMSJATHZ888PD0S0SSTWP4J61TCRJYEVQ0STB))
```

As far as I can tell, that code is valid and well-formed. I have the four lines of the first approach I tried commented out, each with a `;;` at the beginning of the line.

But when I run that code, I get this error:

<img width="685" alt="clarity-book-error-1" src="https://user-images.githubusercontent.com/150330/192283127-8d1bb2fc-91a9-4751-8dd0-787d5ea99534.png">

I don't understand that error, it sure seems fine. If I simply remove the 4 lines of commented code, everything runs fine. But why would having those 4 lines of comments there cause the parser to choke?

----

But even more strangely, if the four commented lines are changed to this:

```clarity
;;   (if (is-eq (map-get? counters who) none)
;;		u0
;;		(unwrap-panic (map-get? counters who))
;;	)
```

You'll notice the contents of those comments are almost identical, except different whitespace (three spaces on the first line, but tabs indenting the other 3 lines).

Weirdly, the parser chokes differently now. Here's the error in *that* case:

<img width="719" alt="clarity-book-error-2" src="https://user-images.githubusercontent.com/150330/192283858-4c03faab-4ff0-42ad-8ef8-92b0c0f7ea00.png">

Unless I'm missing something, it sure seems like indentation whitespace shouldn't matter, and definitely shouldn't matter inside of lines of comments.

Not sure if it would matter, but I'm using Chrome 105 on Windows 10.

**Comment by MarvinJanssen** [comment]
Per https://github.com/clarity-lang/book/issues/19#issuecomment-1258823319, the REPL WASM binary used by the book is old and it exhibits some strange behaviours. Whitespace between the `;;` and the code seems to matter in this version. It is something I ran into before myself. We really need to build a local WASM binary and include it.
