### ISSUE TITLE
Confusing parser error

### ISSUE THREAD

**Issue by getify** [clarity-lang/book#19]
I tried using the `let` function and I'm getting a really confusing/buggy error message being reported.

Here's the code:

```clarity
(define-read-only (get-counter-of (who principal))
	(let ((count (map-get? (counters who))))
		(if
			(is-eq count none) u0 (unwrap-panic count)
		)
	)
)
```

And here's the error reported:

<img width="685" alt="clarity-book-error-3" src="https://user-images.githubusercontent.com/150330/192314888-57f3fcc9-5785-4ab6-a328-1651cb498f0d.png">

I think that `let` syntax is correct, given what I read in the stacks docs. But even if it's an error, the whole `[1;4;31mlet` thing in the error message sure looks like the parser running incorrectly.

**Comment by getify** [comment]
UPDATE: for what it's worth, I think I realized the mistake of my syntax, which was the `map-get?` call and an extra set of parens around `counters who`. Removing those, this code now works without error:

```clarity
(define-read-only (get-counter-of (who principal))
	(let ((count (map-get? counters who)))
		(if
			(is-eq count none) u0 (unwrap-panic count)
		)
	)
)
```

However, that error message above, with `[1;4;31mlet` in it... that still seems like a bug to me.

Also, the red-text highlighting, which I imagine is supposed to be highlighting where the bug is, it sure was confusing that it didn't highlight my `map-get?` expression as being malformed.

**Comment by MarvinJanssen** [comment]
The Clarity REPL used in the book is pretty old. I remember newer WASM builds failing so it has been stuck in time, pulling a pre-built binary from a CDN. Ideally we want the build script to pull the latest REPL and create the build locally. The error highlighting is definitely a bug, but generated by the (old) REPL so it cannot be fixed in the book without upgrading the binary.

**Comment by MarvinJanssen** [comment]
Adding the culprit for brevity: https://github.com/clarity-lang/book/blob/d4918e6610ffb688c000dd2f328d748f391e7fa3/scripts/build.js#L7
