### ISSUE TITLE
Typo in 11.1 Marketplace Setup

### ISSUE THREAD

**Issue by girl-d3v** [clarity-lang/book#34]
Hello, I've found a small error in the highlighted sentence. "using" should be replaced with "user". 

Also, I think this particular sentence could be rewritten for more clarity. 

Example: "Additionally, there is the possibility that a user may try to list an NFT for sale without actually owning it. However, this issue will be addressed by the NFT contract's built-in safeguards."

![ClarityError](https://user-images.githubusercontent.com/67075399/211367085-0d710e96-9318-4fd6-b8a2-a484dadf32c4.png)

**Comment by MarvinJanssen** [comment]
Thanks for the report. PR welcome. 😁

**Comment by MarvinJanssen** [comment]
Fixed in #47.
